name: Sync with upstream

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 실행
  workflow_dispatch:  # 수동 트리거 허용

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/OpenAgentPlatform/Dive.git
          git fetch upstream

      - name: Sync main branch
        run: |
          git checkout main
          git merge upstream/main
          git push origin main

      - name: Sync develop branch
        run: |
          git checkout develop
          git rebase main
          git push origin develop --force